version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: songsdb
    ports:
      - "5432:5432"
  server:
    build: ./server
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: password
      DB_NAME: songsdb
