services:
  server:
    build: ./server
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: pass
      DB_NAME: songsdb
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: songsdb
    ports:
      - "5432:5432"
